force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Exam_Fees_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Exam_Fees_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exam Fees Submitted ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Father_s_phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Father_s_phone_Number__c</fullName>
    <label>Father&apos;s phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Fee_Submited__c.field-meta.xml
<CustomField>
    <fullName>Fee_Submited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fee Submited ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/First_Sem_Back__c.field-meta.xml
<CustomField>
    <fullName>First_Sem_Back__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Sem Back ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/First_Sem_Percentage__c.field-meta.xml
<CustomField>
    <fullName>First_Sem_Percentage__c</fullName>
    <label>First Sem Percentage</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Fourth_Sem_Back__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Sem_Back__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fourth Sem Back ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Fourth_Sem_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Sem_Percentage__c</fullName>
    <label>Fourth Sem Percentage</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Home_Number__c.field-meta.xml
<CustomField>
    <fullName>Home_Number__c</fullName>
    <label>Home Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Is_Donation__c.field-meta.xml
<CustomField>
    <fullName>Is_Donation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Donation ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/OverAll_Grade__c.field-meta.xml
<CustomField>
    <fullName>OverAll_Grade__c</fullName>
    <label>OverAll Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Pending_Overall_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Overall_Amount__c</fullName>
    <label>Pending Overall Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/secions__c.field-meta.xml
<CustomField>
    <fullName>secions__c</fullName>
    <label>secions</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Second_Sem_Back__c.field-meta.xml
<CustomField>
    <fullName>Second_Sem_Back__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Second Sem Back ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Second_Sem_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Second_Sem_Percentage__c</fullName>
    <label>Second Sem Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Subjects_in_which_Back__c.field-meta.xml
<CustomField>
    <fullName>Subjects_in_which_Back__c</fullName>
    <label>Subjects in which Back</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Third_Sem_Back__c.field-meta.xml
<CustomField>
    <fullName>Third_Sem_Back__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Sem Back ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Third_Sem_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Third_Sem_Percentage__c</fullName>
    <label>Third Sem Percentage</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/StudentInsertData.cls
public class StudentInsertData {
      public StudentInsertData(){
        
        //Insert Student Record
        Student__c s1 = new Student__c();
        s1.Student_Name__c = 'Mohd Owais';
        s1.Roll_Number__c = 2345;
        s1.Father_s_Name__c='Jamshed';
        s1.Father_s_phone_Number__c='9838816799';
        s1.Email_Address__c='owaispsit99@gmail.com';
        s1.OverAll_Grade__c ='A';
          //Insert Bank Record
        s1.Account_Number__c = 5555;
        s1.Bank_Name__c ='Axis Bank';
        s1.Bank_Phone_Number__c='1800210';
        s1.Home_Number__c ='800921102';
        s1.City__c ='Kanpur';
        s1.State__c ='Uttar Pradesh';
        s1.Exam_Fees_Submitted__c =True;
        s1.Fee_Submited__c =True;
        s1.Is_Donation__c=False;
        s1.Pending_Exam_Fees__c= 0;
        s1.Pending_Fees_Amount__c =0;
          //Insert Sem Reocrd
        s1.First_Sem_Percentage__c= 80;
        s1.Second_Sem_Percentage__c = 70;
        s1.Third_Sem_Percentage__c =60;
        s1.Fourth_Sem_Percentage__c =50;
        s1.First_Sem_Back__c = True ;
        s1.Second_Sem_Back__c =False;
        s1.Third_Sem_Back__c = True;
        s1.Fourth_Sem_Back__c =True;
        s1.Subjects_in_which_Back__c ='Maths,Physics';
        //Inser Class Record
        s1.secions__c ='C';
        s1.Pending_Overall_Amount__c=0;
        s1.Stream__c='CS';
        insert s1;
        
    }
}